version: "3.9"

services:
  tmsystem:
    build: .
    image: tmsystem
    container_name: tmsystem
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    networks:
      - database_network
    ports:
      - "8080:8080"
  database:
    image: mysql:8.0.34
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: "tmsystem_db"
      MYSQL_ROOT_PASSWORD: "0000"
    networks:
      - database_network
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=0000 --execute=\"use tmsystem_db;\""
      timeout: 5s
      retries: 10

networks:
  database_network:
    name: database_network
    driver: bridge